pipeline {
    agent any

    environment {
        PROJECT_DIR = 'Chapter08/sample1'
    }

    stages {

        stage('Branch Validation') {
            steps {
                script {
                    echo "Current Branch: ${env.BRANCH_NAME}"
                }
            }
        }

        stage('Prepare') {
            steps {

                sh """
                    cd ${PROJECT_DIR}
                    chmod +x gradlew
                """
            }

        }

        stage('Clean') {
            steps {

                sh """
                    cd ${PROJECT_DIR}
                    ./gradlew clean
                """
            }
        }

        stage('Unit Tests') {
            steps {
            
                sh """
                    cd ${PROJECT_DIR}
                    ./gradlew test
                """
            }

        }

        stage('Integration Tests') {
            when {
                not {
                    branch 'master'
                }
            }

            steps {
            

                sh """
                    cd ${PROJECT_DIR}
                    ./gradlew integrationTest
                """
            }
        }

        stage('Checkstyle') {
            when {
                not {
                    branch 'master'
                }
            }

            steps {
                sh """
                    cd ${PROJECT_DIR}
                    ./gradlew checkstyleMain
                """
            }

            post {
                
                always {
                    publishHTML(target: [
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'main.html',
                        reportName: 'Checkstyle Report'
                    ])
                }
            }
        }

        stage('Code Coverage') {
            when {
                branch 'master'
            }

            steps {
            
                sh """
                    cd ${PROJECT_DIR}
                    ./gradlew jacocoTestCoverageVerification
                """
            }

        }
    }

    post {

        always {

            sh """
                cd ${PROJECT_DIR}
                ./gradlew jacocoTestReport || true
            """

            publishHTML(target: [
                reportDir: 'Chapter08/sample1/build/reports/jacoco/test/html',
                reportFiles: 'index.html',
                reportName: 'JaCoCo Report'
            ])

            echo "Branch: ${env.BRANCH_NAME}"
        }

        success {
            echo "tests pass!"
        }

        failure {
            echo "tests fail!"
        }
    }
}
